version: '3.8'
services:
  backend:
    image: fardins24/pet-clinic-rest
    build: ./spring-petclinic-rest
    ports:
      - target: 80
        published: 80
        protocol: tcp
  frontend:
    image: fardins24/pet-clinic-client
    build: ./spring-petclinic-angular
    ports:
      - target: 8080
        published: 8080
        protocol: tcp 