all:
  children:
    managers:
      hosts:
        ansible-manager: # name of the manager instance
    workers:
      hosts:
        worker-1: # name of the worker node instance
        # if needed, add a second worker 
    load-balancer:
      hosts:
        nginx: # name of nginx instance
  vars:
    ansible_user: jenkins
    ansible_ssh_private_key_file: '~/.ssh/ansible_id_rsa'
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

# replace with the correct hosts (AWS Public IPv4 DNS or Address) and users 