- hosts: managers
  become: true
  roles:
  - docker
  - manager
- hosts: workers
  become: true
  roles:
  - docker
  - worker
- hosts: nginx
  become: true
  roles:
  - nginx

# installation of docker in ansible is a must.
# manager, worker, and nginx may not be needed for the playbook.yaml. these could be included during the kubernetes implementation. 
# a new kubernetes role might be useful in this case.